name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm i
          npm run test:lint
          WAOS_NODE_db_uri='mongodb://mongo:27017/WaosNodeTest' npm run test
        env:
          CI: true
